/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author win8
 */
public class DetalleLibro extends javax.swing.JFrame {

    /**
     * Creates new form DetalleLibro
     */
    public DetalleLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DetNombre = new javax.swing.JLabel();
        DetIssn = new javax.swing.JLabel();
        DetTema = new javax.swing.JLabel();
        DetDescrip = new javax.swing.JLabel();
        DetVend = new javax.swing.JLabel();
        DetDisp = new javax.swing.JLabel();
        DetPrecio = new javax.swing.JLabel();
        issn = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        tema = new javax.swing.JTextField();
        descrip = new javax.swing.JTextField();
        vend = new javax.swing.JTextField();
        disp = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        Traducir = new javax.swing.JButton();
        Idiomas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DetNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DetNombre.setText("Nombre:");
        getContentPane().add(DetNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        DetIssn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DetIssn.setText("Issn:");
        getContentPane().add(DetIssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        DetTema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DetTema.setText("Tema:");
        getContentPane().add(DetTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        DetDescrip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DetDescrip.setText("Descripción:");
        getContentPane().add(DetDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        DetVend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DetVend.setText("Cantidad Vendida:");
        getContentPane().add(DetVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        DetDisp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DetDisp.setText("Cantidad Disponible:");
        getContentPane().add(DetDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        DetPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DetPrecio.setText("Precio:");
        getContentPane().add(DetPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));
        getContentPane().add(issn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 150, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 150, -1));

        tema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaActionPerformed(evt);
            }
        });
        getContentPane().add(tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 150, -1));
        getContentPane().add(descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, -1));
        getContentPane().add(vend, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 150, -1));
        getContentPane().add(disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 150, -1));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 150, -1));

        Traducir.setBackground(new java.awt.Color(0, 0, 0));
        Traducir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Traducir.setForeground(new java.awt.Color(255, 255, 255));
        Traducir.setText("Traducir");
        getContentPane().add(Traducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 83, 90, 40));

        Idiomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Idiomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 160, 110, -1));

        jLabel1.setText("Idioma:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Detalle del Libro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 150, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo4.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void temaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DetDescrip;
    private javax.swing.JLabel DetDisp;
    private javax.swing.JLabel DetIssn;
    private javax.swing.JLabel DetNombre;
    private javax.swing.JLabel DetPrecio;
    private javax.swing.JLabel DetTema;
    private javax.swing.JLabel DetVend;
    private javax.swing.JLabel Fondo;
    private javax.swing.JComboBox<String> Idiomas;
    private javax.swing.JButton Traducir;
    private javax.swing.JTextField descrip;
    private javax.swing.JTextField disp;
    private javax.swing.JTextField issn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField tema;
    private javax.swing.JTextField vend;
    // End of variables declaration//GEN-END:variables
}
